### PR TITLE
Ktlint

### PR DESCRIPTION
**Pull request by ccjernigan**
This PR splits into two commits, one to configure ktlint and another to apply ktlint formatting changes.  This should make it easier to review.

As part of enabling ktlint, the version declaration for Kotlin was moved to gradle.properties so that it is accessible to the root build.gradle.kts.  (Version Catalogs don't play nicely with build.gradle.kts).

This code review checklist is intended to serve as a starting point for the author and reviewer, although it may not be appropriate for all types of changes (e.g. fixing a spelling typo in documentation).  For more in-depth discussion of how we think about code review, please see [Code Review Guidelines](../blob/main/docs/CODE_REVIEW_GUIDELINES.md).

# Author

- [x] Self-review: Did you review your own code in GitHub's web interface? _Code often looks different when reviewing the diff in a browser, making it easier to spot potential bugs._
- [ ] Automated tests: Did you add appropriate automated tests for any code changes?
- [ ] Documentation: Did you update documentation as appropriate? (e.g [README.md](../blob/master/README.md), etc.)
- [ ] Rebase and squash: Did you pull in the latest changes from the main branch and squash your commits before assigning a reviewer? _Having your code up to date and squashed will make it easier for others to review. Use best judgement when squashing commits, as some changes (such as refactoring) might be easier to review as a separate commit._

# Reviewer

- [x] Checklist review: Did you go through the code with the [Code Review Guidelines](../blob/master/docs/CODE_REVIEW_GUIDELINES.md) checklist?
- [x] Ad hoc review: Did you perform an ad hoc review?  _In addition to a first pass using the code review guidelines, do a second pass using your best judgement and experience which may identify additional questions or comments. Research shows that code review is most effective when done in multiple passes, where reviewers look for different things through each pass._
- [ ] Automated tests: Did you review the automated tests?
- [ ] Manual tests: Did you review the manual tests?
- [ ] How is Code Coverage affected by this PR? _We encourage you to compare coverage before and after changes and when possible, leave it in a better place._
- [x] Documentation: Did you review Docs and [README.md](../blob/master/README.md) as appropriate?

### CODE REVIEW

**Comment by HonzaR** [comment]
It's great to have Ktlint working on this project! I've just checked it, ran it and it seems to be working as expected. Android studio proposed me some changes - one deprecation and a few variable to value changes. They are not necessary, if you don't like them.

**Comment by HonzaR** [comment]
It's great to have Ktlint working on this project! I've just checked it, ran it and it seems to be working as expected. Android studio proposed me some changes - one deprecation and a few variable to value changes. They are not necessary, if you don't like them.

**Comment by ccjernigan** [comment]
> It's great to have Ktlint working on this project! I've just checked it, ran it and it seems to be working as expected. Android studio proposed me some changes - one deprecation and a few variable to value changes. They are not necessary, if you don't like them.

Awesome for making those Android Studio suggested fixes too 👍

**Review by HonzaR — APPROVED** [review]

**Comment by ccjernigan** [comment]
I am going to do a rebase and merge for this set of changes (instead of squash), since if we need to roll anything back it would be helpful to have the commits be independent.

**Pull request merged**
